# Generated by Django 4.1.4 on 2023-02-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('housename', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('TAMIL NADU', 'TAMIL NADU'), ('GOA', 'GOA'), ('GUJARAT', 'GUJARAT')], default='KERALA', max_length=50)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('offer_active', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='imagestore/')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('normalprice', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default='Wired', on_delete=django.db.models.deletion.CASCADE, to='phase.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, unique=True)),
                ('uemail', models.CharField(max_length=50)),
                ('uphone', models.CharField(max_length=50, null=True)),
                ('upassword', models.CharField(max_length=50)),
                ('uactive', models.BooleanField(default=True)),
                ('uimage', models.ImageField(blank=True, null=True, upload_to='imagestore/')),
                ('uotp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='phase.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordertype', models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Paypal', 'Paypal'), ('Razorpay', 'Razorpay')], default='Cash on delivery', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Return', 'Return')], default='Pending', max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=30)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail'),
        ),
    ]
