# Generated by Django 4.1.4 on 2023-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('image', models.ImageField(default=None, upload_to='imagestore/banner')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel Requested', 'Cancel Requested'), ('Return Requested', 'Return Requested'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
    ]
