# Generated by Django 4.1.4 on 2023-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0003_rename_is_expired_coupon_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
